version = 2

[module]
type = "android-app"
name = "app"
languageLevel = "JAVA_11"
output = "build/classes"

[sourceSets.debug]
scope = "IMPLEMENTATION"
aidl = ["src/debug/aidl"]
assets = ["src/debug/assets"]
java = ["src/debug/java", "src/debug/kotlin"]
jniLibs = ["src/debug/jniLibs"]
res = ["src/debug/res"]
resources = ["src/debug/resources"]

[sourceSets.main]
scope = "IMPLEMENTATION"
aidl = ["src/main/aidl"]
assets = ["src/main/assets"]
java = ["src/main/java", "src/main/kotlin"]
jniLibs = ["src/main/jniLibs"]
res = ["src/main/res"]
resources = ["src/main/resources"]

[sourceSets.release]
scope = "IMPLEMENTATION"
aidl = ["src/release/aidl"]
assets = ["src/release/assets"]
java = ["src/release/java", "src/release/kotlin"]
jniLibs = ["src/release/jniLibs"]
res = ["src/release/res"]
resources = ["src/release/resources"]

[dependencies]
implementation = ["kotlin-stdlib", "com.google.android.material:material:1.14.0", "androidx.appcompat:appcompat:1.8.0", "androidx.lifecycle:lifecycle-runtime-ktx:2.11.0", "androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0", "androidx.fragment:fragment-ktx:1.9.0", "androidx.recyclerview:recyclerview:1.4.0", "androidx.swiperefreshlayout:swiperefreshlayout:1.2.0", "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0", "com.squareup.okhttp3:okhttp:5.5.0", "androidx.security:security-crypto:1.1.0"]
testImplementation = ["junit:junit:4.13.2"]

[android]
namespace = "com.watermarkhu.mijn3park"
compileSdk = 37
minSdk = 23
targetSdk = 35
manifest = "src/main/AndroidManifest.xml"
versionCode = 1
versionName = "1.0"
isApplication = true
manifestPlaceholders = []
buildTypes = [{ name = "debug", debuggable = true, minifyEnabled = false, shrinkResources = false }, { name = "release", debuggable = false, minifyEnabled = false, shrinkResources = false, proguardFiles = ["proguard-android-optimize.txt", "proguard-rules.pro"] }]
